swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # USER (Login) /////////////////////////////////////////////////////////////
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  # USER (Signup) /////////////////////////////////////////////////////////////
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  # USER (Profile) /////////////////////////////////////////////////////////////
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  # TRANSACTION (MONTH) /////////////////////////////////////////////////////////////
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: User transaction for the desired period
      description: Endpoint API for the month desired by the user, If no date is chosen, the current month is called
      parameters:
        - in: header
          description: Attach Bearer JWT token
          name: Authorization
          required: true
          type: string
        - in: query
          description: Desired month
          name: month
          required: false
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid fields
        "401":
          description: Unauthorized - Invalid authentication
        "403":
          description: Forbidden - Access forbidden
        "500":
          description: Internal Server Error
  # TRANSACTION (transactionId) /////////////////////////////////////////////////////////////
  /user/transactions/{transactionId}:
    parameters:
      - in: path
        name: transactionId
        required: true
        type: integer
        description: The ID of transaction selected
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: See the details of the chosen transaction
      description: API endpoint to see the chosen transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction ID chosen by the user
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/SpecificTransactions"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Invalid authentication
        "403":
          description: Forbidden - Access forbidden
        "500":
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update transaction
      description: Endpoint API to add, modify or delete a category or notes
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction ID chosen by the user
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UpdateTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction modfication successfully
          schema:
            $ref: "#/definitions/SpecificTransactions"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Invalid authentication
        "403":
          description: Forbidden - Access forbidden
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: Transaction id
            example: 18
          date:
            type: string
            format: date-time
            description: Transaction date and date-time
            example: "2023-28-25T11:08:55.788F"
          description:
            type: string
            description: Transaction description
            example: Telephone bill
          amount:
            type: integer
            format: int32
            description: Transaction amount
            example: 70
          balance:
            type: string
            description: Account balance
            example: 140 000
          type:
            type: string
            description: Transaction type
            example: Telephone Bill
          category:
            type: string
            description: Transaction category
            example: Bill
          notes:
            type: string
            description: Transaction personnal notes
            example: monthly telephone bill
  SpecificTransactions:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: Transaction id
            example: 40
          date:
            type: string
            format: date-time
            description: Transaction date and date-time
            example: "2023-28-25T11:08:55.788F"
          description:
            type: string
            description: Transaction description
            example: Restaurant Le Maroille
          amount:
            type: integer
            format: int32
            description: Transaction amount
            example: 140
          balance:
            type: string
            description: Account balance
            example: 120 000
          type:
            type: string
            description: Transaction type
            example: Restaurant
          category:
            type: string
            description: Transaction category
            example: Food
          notes:
            type: string
            description: Transaction personnal notes
            example: AfterWork restaurant
  UpdateTransaction:
    properties:
      category:
        type: string
        description: Add/Update/Delete category of transaction
      notes:
        type: string
        description: Add/Update/Delete notes of transaction
